import { Router, type IRouter } from "express";
import healthRouter from "./health";
import shopifyRouter from "./shopify";
import pushRouter from "./push";
import eventsRouter from "./events";
import bambuRouter from "./bambu";
import pihubRouter from "./pihub";
import cameraRouter from "./camera";
import discordRouter from "./discord";
import squareRouter from "./square";
import socialRouter from "./social";
import tapoRouter from "./tapo";
import filamentDbRouter from "./filamentDb";
import visionRouter from "./vision";
import emailRouter from "./email";
import catalogRouter from "./catalog";
import etsyGmailRouter from "./etsy-gmail";
import aiRouter from "./ai";
import adminRouter from "./admin";
const router: IRouter = Router();

router.use(healthRouter);
router.use("/shopify", shopifyRouter);
router.use("/push", pushRouter);
router.use("/events", eventsRouter);
router.use("/bambu", bambuRouter);
router.use("/pihub", pihubRouter);
router.use("/camera", cameraRouter);
router.use("/discord", discordRouter);
router.use("/square", squareRouter);
router.use("/social", socialRouter);
router.use("/tapo", tapoRouter);
router.use("/filament-db", filamentDbRouter);
router.use("/vision", visionRouter);
router.use("/email", emailRouter);
router.use("/catalog", catalogRouter);
router.use("/etsy", etsyGmailRouter);
router.use("/ai", aiRouter);
router.use("/admin", adminRouter);

export default router;
